# Generated by Django 2.1.2 on 2018-10-24 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_manager_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('screen', 'seat_number', 'row')},
        ),
    ]
